## Symphony
## Author: vyrx
## Theme: Nordic


[colors]
[colors.primary]
background = '#2e3440'
foreground = '#d8dee9'

# Normal colors
[colors.normal]
black = '#3b4252'
red = '#bf616a'
green = '#a3be8c'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#88c0d0'
white = '#e5e9f0'

# Bright colors
[colors.bright]
black = '#4c566a'
red = '#bf616a'
green = '#a3be8c'
yellow = '#d08770'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#8fbcbb'
white = '#eceff4'

[colors.selection]
background = '#434c5e'
foreground = '#d8dee9'
