# Colors from Symphony
general.import = ["~/.config/symphony/current/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.8

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = {family = "JetBrainsMono Nerd Font", style = "bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 9

# previous "font = CaskaydiaCove Nerd Font"
