# Symphony by vyrx
# Theme: Kanagawa

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "colors"

format = """
$username$hostname$directory$git_branch$c$cpp$golang$haskell$java$lua$nodejs$nim$rust$scala$python
$character"""

[palettes.colors]
primary = '#7e9cd8'
secondary = '#957fb8'
error = '#c34043'


[username]
show_always = true
style_user = "fg:primary"
style_root = "fg:error"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = "fg:primary"
format = "[@$hostname]($style)"

[directory]
style = "fg:primary"
format = " [@ $path]($style)"
truncation_length = 1
home_symbol = "~"
truncate_to_repo = false

[git_branch]
style = "fg:secondary"
format = " on [$symbol$branch]($style)"

[c]
symbol = "î˜"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = "î˜"
format = '[ $symbol ($version) ]($style)'
disabled = false

[docker_context]
symbol = "ïŒˆ"
format = '[ $symbol $context ]($style)'

[golang]
symbol = "î˜§"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î·"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰–"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = "î˜ "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "ğŸ¦€"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ·"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "ğŸ"
format = '[ $symbol ($version) ]($style)'

[character]
success_symbol = "[âœ](green)"
error_symbol = "[âœ](red)"
vicmd_symbol = "[âœ](green)"
format = "[$symbol]($style) "
