# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e8" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d274ff", bg = "#d274ff" }
marker_cut = { fg = "#f3daff", bg = "#f3daff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d7bde4", bg = "#d7bde4" }

# Count
count_copied = { fg = "#251431", bg = "#f3daff" }
count_cut = { fg = "#251431", bg = "#f3daff" }
count_selected = { fg = "#00325a", bg = "#d7bde4" }

# Border
border_symbol = " "
border_style  = { fg = "#a1c9fd" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "" }

# Permissions
perm_type = { fg = "#5875a5" }
perm_read = { fg = "#c141ff" }
perm_write = { fg = "#9550b8" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#3988ff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a1c9fd", bg = "#37393e" }
progress_error = { fg = "#ffb4ab", bg = "#37393e" }

[mode]
# Mode
normal_main = { bg = "#a1c9fd", fg = "#00325a", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Select mode
select_main = { bg = "#bbc7db", fg = "#253141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Unset mode
unset_main = { bg = "#d7bde4", fg = "#3b2947", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a1c9fd" }
active = { fg = "#d7bde4", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a1c9fd" }
value = { fg = "#e1e2e8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#a1c9fd", bold = true, bg = "#111418" }
inactive = { fg = "#bbc7db", bg = "#111418" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#a1c9fd", bg = "#00325a" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a1c9fd" }
title = {}
hovered = { fg = "#f3daff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a1c9fd" }
rest = { fg = "#00325a" }
desc = { fg = "#e1e2e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e2e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e8" }
run = { fg = "#e1e2e8" }
footer = { fg = "#253141", bg = "#bbc7db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d7bde4" }
title_warn = { fg = "#a1c9fd" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e1e2e8" },
    { url = "*/", fg = "#a1c9fd" },
]

# : ]]]
