[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/dotfiles/themes/dynamic/.config/hypr/theme/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/dotfiles/themes/dynamic/.config/kitty/colors.conf'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/dotfiles/themes/dynamic/.config/btop/themes/current.theme'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/dotfiles/themes/dynamic/.config/yazi/theme.toml'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/dotfiles/themes/dynamic/.config/cava/config'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel_theme.ini'
output_path = '~/dotfiles/themes/dynamic/.config/fuzzel/fuzzel_theme.ini'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/dotfiles/themes/dynamic/.config/ghostty/theme'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/themes/dynamic/.config/waybar/colors.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/dotfiles/themes/dynamic/.config/starship.toml'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/dotfiles/themes/dynamic/.config/rofi/colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/themes/dynamic/.config/swaync/matugen/colors.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/themes/dynamic/.config/gtk-3.0/colors.css'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty-colors.toml'
output_path = '~/dotfiles/themes/dynamic/.config/alacritty/colors.toml'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/themes/dynamic/.config/gtk-4.0/colors.css'

[templates.rmpc]
input_path = '~/.config/matugen/templates/rmpc-theme.ron'
output_path = '~/dotfiles/themes/dynamic/.config/rmpc/themes/current.ron'

[templates.pywalfox-json]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/dotfiles/themes/dynamic/.cache/wal/colors.json'

[templates.pywalfox-colors]
input_path = '~/.config/matugen/templates/pywalfox-colors'
output_path = '~/dotfiles/themes/dynamic/.cache/wal/colors'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-color.css'
output_path = '~/dotfiles/themes/dynamic/.config/vesktop/themes/symphony-discord.css'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian-theme.css'
output_path = '~/dotfiles/themes/dynamic/.config/obsidian/theme.css'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify-colors.ini'
output_path = '~/dotfiles/themes/dynamic/.config/spicetify/Themes/symphony/color.ini'



