# Symphony by vyrx / Theme: Forest / https://github.com/vyrx-dev
# : Manager [[[

[mgr]
cwd = { fg = "#fdfffd" }

# Find
find_keyword = { fg = "#55c695", bold = true, italic = true, underline = true }
find_position = { fg = "#55c695", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7db9bd", bg = "#7db9bd" }
marker_cut = { fg = "#c5e3e5", bg = "#c5e3e5" }
marker_marked = { fg = "#55c695", bg = "#55c695" }
marker_selected = { fg = "#8fc78d", bg = "#8fc78d" }

# Count
count_copied = { fg = "#020802", bg = "#c5e3e5" }
count_cut = { fg = "#020802", bg = "#c5e3e5" }
count_selected = { fg = "#020802", bg = "#8fc78d" }

# Border
border_symbol = " "
border_style  = { fg = "#5fb35b" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "" }

# Permissions
perm_type = { fg = "#55c695" }
perm_read = { fg = "#5fb35b" }
perm_write = { fg = "#c8d56e" }
perm_exec = { fg = "#bf5a7c" }
perm_sep = { fg = "#7db9bd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#5fb35b", bg = "#1a2a1a" }
progress_error = { fg = "#bf5a7c", bg = "#1a2a1a" }

[mode]
# Mode
normal_main = { bg = "#5fb35b", fg = "#020802", bold = true }
normal_alt  = { bg = "#1a2a1a", fg = "#8fc78d" }

# Select mode
select_main = { bg = "#7db9bd", fg = "#020802", bold = true }
select_alt  = { bg = "#1a2a1a", fg = "#8fc78d" }

# Unset mode
unset_main = { bg = "#c8d56e", fg = "#020802", bold = true }
unset_alt  = { bg = "#1a2a1a", fg = "#8fc78d" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#5fb35b" }
active = { fg = "#55c695", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#5fb35b" }
value = { fg = "#fdfffd" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#5fb35b", bold = true, bg = "#020802" }
inactive = { fg = "#4a7a4a", bg = "#020802" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#5fb35b", bg = "#0a1a0a" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#5fb35b" }
title = {}
hovered = { fg = "#55c695", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#1a2a1a" }
cand = { fg = "#5fb35b" }
rest = { fg = "#4a7a4a" }
desc = { fg = "#fdfffd" }
separator = " ‚ñ∂ "
separator_style = { fg = "#fdfffd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#fdfffd" }
run = { fg = "#fdfffd" }
footer = { fg = "#020802", bg = "#7db9bd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#55c695" }
title_warn = { fg = "#c8d556" }
title_error = { fg = "#bf5a7c" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#7db9bd" },

    # Media
    { mime = "{audio,video}/*", fg = "#c8d556" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#c8d56e" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#5fb35b" },

    # Special files
    { url = "*", is = "orphan", bg = "#4a0a0a" },
    { url = "*", is = "exec", fg = "#55c695" },

    # Fallback
    { url = "*", fg = "#fdfffd" },
    { url = "*/", fg = "#5fb35b" },
]

# : ]]]
