## Symphony
## Author: vyrx
## Theme: Zen


[colors.primary]
background = '#0f0f0f'
foreground = '#e8e8ed'

[colors.normal]
black = '#1c1c1e'
red = '#5c5c5e'
green = '#98989a'
yellow = '#7a7a7c'
blue = '#6c6c6e'
magenta = '#86868a'
cyan = '#a8a8ac'
white = '#d1d1d6'

[colors.bright]
black = '#48484a'
red = '#6e6e70'
green = '#aeaeb0'
yellow = '#8e8e90'
blue = '#828284'
magenta = '#9c9ca0'
cyan = '#bebec2'
white = '#f5f5f7'

[colors.hints.start]
foreground = "CellBackground"
background = "CellForeground"

[colors.hints.end]
foreground = "CellBackground"
background = "CellForeground"

[colors.search.matches]
foreground = '#0f0f0f'
background = '#bebec2'

[colors.search.focused_match]
foreground = '#0f0f0f'
background = '#f5f5f7'
